id: PE9517942
initial_creation_type: ocr
source_metadata:
  volumes:
    c3d1b62e879f481889fd5b1075c0732d:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
